repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: fix-byte-order-marker
    - id: check-case-conflict
    - id: check-merge-conflict
    - id: end-of-file-fixer
    - id: mixed-line-ending
    - id: trailing-whitespace
    - id: check-ast
    - id: check-json
    - id: check-yaml
    - id: check-symlinks
    - id: pretty-format-json
      args: ["--autofix", "--no-ensure-ascii"]
- repo: https://github.com/psf/black
  rev: 23.3.0
  hooks:
    - id: black
      args: ["--line-length", "120"]
- repo: https://github.com/asottile/pyupgrade
  rev: v3.4.0
  hooks:
  - id: pyupgrade
    args: [--py310-plus]
- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
  - id: isort
    args: ["--line-length", "120", "--profile", "black", "--filter-files"]
    name: isort
- repo: https://github.com/Lucas-C/pre-commit-hooks
  rev: v1.5.1
  hooks:
    - id: forbid-crlf
    - id: remove-crlf
- repo: https://github.com/nbQA-dev/nbQA
  rev: "1.7.0"
  hooks:
    - id: nbqa-black
      args: [--nbqa-skip-celltags=before-import]
    - id: nbqa-pyupgrade
      args: [--py39-plus]
    - id: nbqa-isort
      args: [--nbqa-skip-celltags=before-import, --profile=black]
    - id: nbqa-check-ast
    - id: nbqa
      entry: nbqa docformatter -i
      name: nbqa-docformatter
      alias: nbqa-docformatter
      additional_dependencies: [docformatter==1.5.0]
- repo: https://github.com/srstevenson/nb-clean
  rev: "2.4.0"
  hooks:
    - id: nb-clean
      args: ["--remove-empty-cells", "--preserve-cell-metadata", "tags", "slideshow", "--"]
